ARG version=3.6-alpine
FROM python:${version}


ENV FLASK_APP=/main.py

COPY main.py /

RUN pip install Flask==1.1.2
RUN pip install requests==2.22.0
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev

RUN pip install psycopg2-binary

EXPOSE 80/tcp


ENTRYPOINT ["flask","run","-h","0.0.0.0","-p","80"]
