apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
  - image: postgress:latest
    imagePullPolicy: Never
    name: postgres
    envFrom:
    - configMapRef:
        name: postgres-config
