- hosts: localhost
  connection: local 
  
  tasks:
    - name: install certain python modules for docker
      pip:
         name: docker
         state: present
      become: yes

    - name: "systemctl start"
      service:
        name: docker
        state: started
        enabled: yes
      become: yes 
      
    - name: "Swarm"
      docker_swarm:
        state: present
        advertise_addr: 192.168.0.16
      become: yes
    

    - name: Build image nginx
      docker_image:
        name: web_image 
        build:
          path: /var/lib/jenkins/workspace/ansible-demo/Dockerfile_nginx
      become: yes
      source: build

    - name: Build image backend
      docker_image:
        name: backend
        build:
          path: /var/lib/jenkins/workspace/ansible-demo/Dockerfile_main
      become: yes
      source: build

    - name: Build image postgres
      docker_image:
        name: postgress
        build:
          path: /var/lib/jenkins/workspace/ansible-demo/Dockerfile_postgres      
      become: yes
      source: build

    - name: "Deploy service" 
      shell: docker stack deploy --compose-file /var/lib/jenkins/workspace/ansible-demo stack
      become: yes  
     
