- hosts: localhost
  connection: local 
  
  tasks:
    - name: install certain python modules for docker
      pip:
         name: docker
         state: present
      become: yes
    
    - name: Install latest docker python bindings
      pip:
        name: "{{ packages }}"
        executable: pip3
        state: latest
      vars:
        packages:
        - docker
        - jsondiff
         
      become: true
    - name: "systemctl start"
      service:
        name: docker
        state: started
        enabled: yes
      become: yes 
      
    - name: "Swarm"
      docker_swarm:
        state: present
        advertise_addr: 192.168.0.16
      become: yes
    

    - name: Build image nginx
      become: yes
      docker_image:
        name: web_image 
        build:
          path: /var/lib/jenkins/workspace/ansible-demo/
          dockerfile: Dockerfile_nginx
        source: build
        state: present
     
      

    - name: Build image backend
      become: yes
      docker_image:
        name: backend
        build:
          path: /var/lib/jenkins/workspace/ansible-demo/
          dockerfile: Dockerfile_main
        source: build  
        state: present
  

    - name: Build image postgres
      become: yes
      docker_image:
        name: postgress
        build:
          path: /var/lib/jenkins/workspace/ansible-demo/
          dockerfile: Dockerfile_postgres
        source: build      
        state: present
   
    - name: Deploy
      become: yes
      docker_stack:
              state: present
              name: stack
              compose:
                      - /var/lib/jenkins/workspace/ansible-demo/docker_compose.yml

            
    

     
    
      
                 
