- hosts: localhost
  connection: local 
  
  tasks:
    - name: "ping"
      ping:
    
      
    - name: "Swarm"
      docker_swarm:
        state: present
        advertise_addr: 192.168.0.16
      become: yes

    - name: "Build web_image"
      shell: docker build -t web_image -f /var/lib/jenkins/workspace/ansible-demo .
      become: yes

    - name: "build image backend"
      shell: docker build -t backend -f /var/lib/jenkins/workspace/ansible-demo .
      become: yes
           
    - name: "build image postgres" 
      shell: docker build -t postgress -f /var/lib/jenkins/workspace/ansible-demo . 
      become: yes
   
    - name: "Deploy service" 
      shell: docker stack deploy --compose-file /var/lib/jenkins/workspace/ansible-demo stack
      become: yes  
     
